[workspace]
members = [
    "userspace/ksud",
    "userspace/ksuinit",
]
default-members = [
    "userspace/ksud",
    "userspace/ksuinit",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
log = "0.4"

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", rev = "1a661633f11a261ff9c00b40875ef72f1cbec818" }

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"

[profile.release.package.ksud]
codegen-units = 1
