#ifndef __KSU_UAPI_SELINUX_H
#define __KSU_UAPI_SELINUX_H

#include <linux/types.h>

static const __u32 KSU_SEPOLICY_CMD_NORMAL_PERM = 1;
static const __u32 KSU_SEPOLICY_CMD_XPERM = 2;
static const __u32 KSU_SEPOLICY_CMD_TYPE_STATE = 3;
static const __u32 KSU_SEPOLICY_CMD_TYPE = 4;
static const __u32 KSU_SEPOLICY_CMD_TYPE_ATTR = 5;
static const __u32 KSU_SEPOLICY_CMD_ATTR = 6;
static const __u32 KSU_SEPOLICY_CMD_TYPE_TRANSITION = 7;
static const __u32 KSU_SEPOLICY_CMD_TYPE_CHANGE = 8;
static const __u32 KSU_SEPOLICY_CMD_GENFSCON = 9;

static const __u32 KSU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW = 1;
static const __u32 KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY = 2;
static const __u32 KSU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW = 3;
static const __u32 KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT = 4;

static const __u32 KSU_SEPOLICY_SUBCMD_XPERM_ALLOW = 1;
static const __u32 KSU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW = 2;
static const __u32 KSU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT = 3;

static const __u32 KSU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE = 1;
static const __u32 KSU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE = 2;

static const __u32 KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE = 1;
static const __u32 KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER = 2;

#endif
