.TH "sepol_check_context" "3" "15 March 2005" "sds@tycho.nsa.gov" "SE Linux binary policy API documentation"
.SH "NAME"
sepol_check_context \- Check the validity of a security context against a binary policy.
.SH "SYNOPSIS"
.B #include <sepol/sepol.h>
.sp
.BI "int sepol_check_context(const char *" context ");"
.sp
.BI "int sepol_set_policydb_from_file(FILE *" fp ");"

.SH "DESCRIPTION"
.B sepol_check_context
checks the validity of a security context against a binary policy
previously loaded from a file via
.B sepol_set_policydb_from_file.
It is used by 
.B setfiles -c
to validate a file contexts configuration against the binary policy
upon policy builds.  For validating a context against the active
policy on a SELinux system, use
.B security_check_context
from libselinux instead.

.SH "RETURN VALUE"
Returns 0 on success or \-1 with errno set otherwise.
