#!/usr/bin/env python3

from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUTS = [
    ROOT / "include" / "uapi" / "feature.h",
    ROOT / "include" / "uapi" / "app_profile.h",
    ROOT / "include" / "uapi" / "supercall.h",
]
OUTPUT = ROOT / "ksu_uapi.h"


def strip_header_boilerplate(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    skipped_ifndef = False
    skipped_define = False

    for line in lines:
        stripped = line.strip()

        if not skipped_ifndef and stripped.startswith("#ifndef "):
            skipped_ifndef = True
            continue
        if skipped_ifndef and not skipped_define and stripped.startswith("#define "):
            skipped_define = True
            continue
        if stripped == "#endif":
            continue
        if stripped in {
            "#include <linux/types.h>",
            "#include <linux/ioctl.h>",
            '#include "uapi/feature.h"',
            '#include "uapi/app_profile.h"',
        }:
            continue

        out.append(line)

    while out and out[0] == "":
        out.pop(0)
    while out and out[-1] == "":
        out.pop()

    return out


def main() -> int:
    merged: list[str] = [
        "#ifndef __KSU_UAPI_H",
        "#define __KSU_UAPI_H",
        "",
        "/* Auto-generated by tools/gen_ksu_uapi.py. Do not edit directly. */",
        "",
        "#include <linux/ioctl.h>",
        "#include <linux/types.h>",
        "",
    ]

    for path in INPUTS:
        merged.append(f"/* Source: {path.relative_to(ROOT)} */")
        merged.extend(strip_header_boilerplate(path))
        merged.append("")

    merged.append("#endif")
    merged.append("")

    OUTPUT.write_text("\n".join(merged), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
