name: LKM-5.15
on:
  workflow_dispatch:
  push:
    branches: ["main", "ci", "checkci"]
    paths:
      - ".github/workflows/build-lkm.yml"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-lkm.yml"
  workflow_call:
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android13-5.15"
            sub_level: 74
            os_patch_level: 2023-01
          - version: "android13-5.15"
            sub_level: 137
            os_patch_level: 2023-12
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: true
