name: Clippy check

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/clippy.yml'
      - 'userspace/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/clippy.yml'
      - 'userspace/**'

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: rustup update stable
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: userspace/ksud

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29

      - name: Run clippy
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android
          source .github/scripts/setup-rust-build.sh aarch64-linux-android 26
          source .github/scripts/setup-rust-build.sh x86_64-linux-android 26
          cargo clippy --manifest-path userspace/ksud/Cargo.toml --target aarch64-linux-android --release
          cargo clippy --manifest-path userspace/ksud/Cargo.toml --target x86_64-linux-android --release
          cargo clippy --manifest-path userspace/ksuinit/Cargo.toml --target aarch64-linux-android --release
          cargo clippy --manifest-path userspace/ksuinit/Cargo.toml --target x86_64-linux-android --release
