# About the REST API

Get oriented to the REST API documentation.

You can use GitHub's API to build scripts and applications that automate processes, integrate with GitHub, and extend GitHub. For example, you could use the API to triage issues, build an analytics dashboard, or manage releases.

Each REST API endpoint is documented individually, and the endpoints are categorized by the resource that they primarily affect. For example, you can find endpoints relating to issues in [REST API endpoints for issues](/en/rest/issues).

## Getting started with the REST API

**If you are new to REST APIs**, you may find it helpful to refer to the Quickstart or Getting Started guide for an introduction. For more information, see:

* [Quickstart for GitHub REST API](/en/rest/quickstart)
* [Getting started with the REST API](/en/rest/guides/getting-started-with-the-rest-api)

**If you are familiar with REST APIs** but new to GitHub's REST API, you may find it helpful to refer to the authentication documentation. For more information, see:

* [Authenticating to the REST API](/en/rest/overview/authenticating-to-the-rest-api)

**If you are building scripts or applications** that use the REST API, you may find some of the following guides helpful. For examples of scripting with the REST API, see:

* [Scripting with the REST API and JavaScript](/en/rest/guides/scripting-with-the-rest-api-and-javascript)
* [Scripting with the REST API and Ruby](/en/rest/guides/scripting-with-the-rest-api-and-ruby)
* [Building a GitHub App that responds to webhook events](/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-github-app-that-responds-to-webhook-events)
* [Building a CLI with a GitHub App](/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-cli-with-a-github-app)
* [Automatically redelivering failed deliveries for a repository webhook](/en/webhooks/using-webhooks/automatically-redelivering-failed-deliveries-for-a-repository-webhook)

For a list of libraries to facilitate scripting with the REST API, see [Libraries for the REST API](/en/rest/overview/libraries-for-the-rest-api).

If you are building scripts or applications that use the REST API, you might also be interested in using webhooks to get notified about events or a GitHub App to access resources on behalf of a user or in an organization. For more information, see [About webhooks](/en/webhooks/about-webhooks) and [Deciding when to build a GitHub App](/en/apps/creating-github-apps/about-creating-github-apps/deciding-when-to-build-a-github-app).

## Further reading

* [Comparing GitHub's REST API and GraphQL API](/en/rest/overview/comparing-githubs-rest-api-and-graphql-api)
* [Best practices for using the REST API](/en/rest/guides/best-practices-for-using-the-rest-api)
* [Keeping your API credentials secure](/en/rest/overview/keeping-your-api-credentials-secure)
* [Troubleshooting the REST API](/en/rest/overview/troubleshooting-the-rest-api)# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow lets you generate SLSA provenance file for your project.
# The generation satisfies level 3 for the provenance requirements - see https://slsa.dev/spec/v0.1/requirements
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.
# For more information about SLSA and how it improves the supply-chain, visit slsa.dev.

name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Build artifacts
        run: |
            # These are some amazing artifacts.
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2

      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files=$(ls artifact*)
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
