name: Build ksud
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest
      pack_lkm:
        required: false
        type: boolean
        default: false
      pack_ksuinit:
        required: false
        type: boolean
        default: false
      use_cache:
        required: false
        type: boolean
        default: true
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v7
    
    - name: Prepare LKM fies
      if: ${{ inputs.pack_lkm }}
      run: |
        cp android*-lkm/*_kernelsu.ko ./userspace/ksud/bin/aarch64/
    
    - name: Prepare ksuinit
      if: ${{ inputs.pack_ksuinit }}
      run: |
        mv ksuinit/*/release/ksuinit ./userspace/ksud/bin/aarch64/
        
    - name: Setup rustup
      run: |
        rustup update stable
        rustup target add ${{ inputs.target }}

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: userspace/ksud
        cache-targets: false

    - name: Build ksud
      run: |
        TRIPLE=${{ inputs.target }}
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#environment-variables-2
        # We use the latest ndk that the image provided
        echo "ANDROID_NDK_LATEST_HOME=$ANDROID_NDK_LATEST_HOME"
        LLVM_PATH=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
        CLANG_PATH=$LLVM_PATH/${TRIPLE}26-clang
        UTRIPLE=$(echo $TRIPLE | sed 's/-/_/g')
        UUTRIPLE=$(echo $UTRIPLE | tr a-z A-Z)

        export CC_$UTRIPLE=$CLANG_PATH
        export CXX_$UTRIPLE=${CLANG_PATH}++
        export AR_$UTRIPLE=$LLVM_PATH/llvm-ar
        export CARGO_TARGET_${UUTRIPLE}_LINKER=$CLANG_PATH
        cargo build --target $TRIPLE --release --manifest-path ./userspace/ksud/Cargo.toml

    - name: Upload ksud artifact
      uses: actions/upload-artifact@v6
      with:
        name: ksud-${{ inputs.target }}
        path: userspace/ksud/target/**/release/ksud*
