name: Build ksud
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      pack_lkm:
        required: false
        type: boolean
        default: false
      pack_ksuinit:
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v8
    
    - name: Prepare LKM files
      if: ${{ inputs.pack_lkm }}
      run: |
        cp android*-lkm/*_kernelsu.ko ./userspace/ksud/bin/aarch64/
    
    - name: Prepare ksuinit
      if: ${{ inputs.pack_ksuinit }}
      run: |
        mv ksuinit/*/release/ksuinit ./userspace/ksud/bin/aarch64/
        
    - name: Setup rustup
      run: |
        rustup update stable
        rustup target add ${{ inputs.target }}

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: userspace/ksud
        cache-targets: false

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r29

    - name: Build ksud
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        source .github/scripts/setup-rust-build.sh ${{ inputs.target }} 26
        cargo build --target $TRIPLE --release --manifest-path ./userspace/ksud/Cargo.toml

    - name: Upload ksud artifact
      uses: actions/upload-artifact@v7
      with:
        name: ksud-${{ inputs.target }}
        path: target/${{ inputs.target }}/release/ksud
