name: Build ksuinit
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Setup rustup
      run: |
        rustup update stable
        rustup target add aarch64-unknown-linux-musl

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: userspace/ksuinit
        cache-targets: false

    - name: Build ksuinit
      run: |
        cd userspace
        cargo ksuinit-build

    - name: Upload ksuinit artifact
      uses: actions/upload-artifact@v6
      with:
        name: ksuinit
        path: userspace/target/**/release/ksuinit*
